### ISSUE TITLE
JavaScript error on menu items

### ISSUE THREAD

**Issue by mitchellknight** [mitchas/ffftp#4]
**How to reproduce:** Open ffftp.app. Close the window. Select a menu item like Action → Connect or Dev → Dev Tools.

**Error Message:** 

> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Attempting to call a function in a renderer window that has been closed or released. Function provided here: undefined at callIntoRenderer (/ffftp.app/Contents/Resources/electron.asar/browser/rpc-server.js:186:19) at MenuItem.click (/ffftp.app/Contents/Resources/electron.asar/browser/api/menu-item.js:82:16)
    at Function.executeCommand (/ffftp.app/Contents/Resources/electron.asar/browser/api/menu.js:119:40)

**Recommendation:** If closing the window doesn't close the app (somewhat common on macOS apps), then running any command with the window closed should trigger the window to open before the command is executed.

**Comment by lukasoppermann** [comment]
Same error here.

<img width="414" alt="screen shot 2017-02-10 at 10 41 08" src="https://cloud.githubusercontent.com/assets/813754/22821934/832bfe48-ef7d-11e6-9a9c-a1c053b5da89.png">
